# Generated by Django 4.1 on 2022-08-18 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='photo',
            field=models.ImageField(default=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='questions',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='userid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, verbose_name='Вопрос'),
        ),
    ]
