# Generated by Django 4.1 on 2022-09-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_question_comments_quest_alter_comments_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Уровень образования',
                'verbose_name_plural': 'Уровни образования',
            },
        ),
    ]
